#tab_spaces = 2

newline_style = "Unix"
# require the shorthand instead of it being optional
use_field_init_shorthand = true
#use_try_shorthand = true
use_small_heuristics = "Max"

#wrap_comments = true
#comment_width = 100
#error_on_line_overflow = true

#format_code_in_doc_comments = true
#format_macro_bodies = true
#format_macro_matchers = true
#format_strings = true

# better grepping
#imports_granularity = "Module"
# quicker manual lookup
#group_imports = "StdExternalCrate"
# why use an attribute if a normal doc comment would suffice?
#normalize_doc_attributes = true
# trailing semicolon for explicit returns
#trailing_semicolon = true
